module.exports = {
 
  GET_ERRORS: "GET_ERRORS",
  GET_USER_DATA: "GET_USER_DATA",
  ADD_USER_DATA: "ADD_USER_DATA",
  GET_USER: "GET_USER",
  ADD_DATA_SUCCESS: "ADD_DATA_SUCCESS",
  DELETE_USER_DATA: "DELETE_USER_DATA",
  FETCH_USER_DATA : "FETCH_USER_DATA"
};
